django/website/urls.py
from django.conf.urls import include, url
# from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import logframe.urls
import api.urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('contacts.auth_urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(api.urls)),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^export/', include('export.urls')),
    url(r'', include(logframe.urls)),

    # This requires that static files are served from the 'static' folder.
    # The apache conf is set up to do this for you, but you will need to do it on
    # dev
    url(r'favicon.ico', RedirectView.as_view(
        url='{0}images/favicon.ico'.format(settings.STATIC_URL), permanent=True)),

    # LAST - redirect from root URL to the logframe app
    # url(r'^$', RedirectView.as_view(url=reverse_lazy('logframe-overview', args=(1,)))),
    url(r'', include('dashboard.urls')),
]

django/website/contacts/models.py
import os.path

from django.db.models import (
    CharField, TextField, EmailField,
    FileField, DateTimeField, BooleanField,
    ImageField, ForeignKey, OneToOneField, Model
)
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.utils import timezone
from django.utils.deconstruct import deconstructible

from main.upload_handler import UploadToHandler
from .countries import COUNTRIES, NATIONALITIES


def get_user_fields(instance):
    return (instance.business_email, instance.last_name, instance.first_name)


@deconstructible
class PictureUploadHandler(object):
    path_base = ''

    def __init__(self, path_base):
        self.path_base = path_base

    def __call__(self, instance, filename):
        name = "_".join([instance.last_name, instance.first_name]).strip('_')
        prefix = name if name else instance.business_email
        new_filename = "{0}_{1}".format(prefix, filename)
        new_path = os.path.join(self.path_base, new_filename)
        return new_path


# Managers
class UserManager(BaseUserManager):
    def _create_user(self, business_email=None, password=None,
                     is_active=True, is_staff=False, is_superuser=False,
                     **extra_fields):
        now = timezone.now()
        if not business_email:
            raise ValueError('The given business_email must be set')
        email = UserManager.normalize_email(business_email)
        user = self.model(business_email=email, is_staff=is_staff,
                          is_active=is_active, is_superuser=is_superuser,
                          last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, business_email=None, password=None, **extra_fields):
        return self._create_user(business_email, password, **extra_fields)

    def create_superuser(self, business_email, password, **extra_fields):
        return self._create_user(business_email, password, is_staff=True,
                                 is_superuser=True, **extra_fields)


# Models
class User(AbstractBaseUser, PermissionsMixin):
    # Account info
    business_email = EmailField(unique=True)
    is_staff = BooleanField(
        verbose_name='staff status',
        default=False,
        help_text=('Designates whether the user can log into this admin '
                   'site.'))
    is_active = BooleanField(
        verbose_name='active',
        default=True,
        help_text=('Designates whether this user should be treated as '
                   'active. Unselect this instead of deleting accounts.'))
    date_joined = DateTimeField(default=timezone.now)

    # general contact information
    first_name = CharField(max_length=50)
    last_name = CharField(max_length=50)

    # Managers and book-keeping

    USERNAME_FIELD = 'business_email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    def get_full_name(self):
        return u"{0} {1}".format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.get_full_name()

    @property
    def email(self):
        return self.business_email

    @property
    def preferences(self):
        try:
            preferences = self._preferences
        except UserPreferences.DoesNotExist:
            preferences = UserPreferences.objects.create(user=self)
        return preferences


class UserPreferences(Model):
    user = OneToOneField(User, related_name='_preferences')
    last_viewed_logframe = ForeignKey('logframe.LogFrame', null=True)

django/website/main/templates/base.html
{% load assets %}
{% load settings_value %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% settings_value "SITE_NAME" %} MIS {% block title %}{% endblock %}</title>
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <script>window.Aptivate = {};</script>
</head>
<body{% block body_attrs %}{% endblock %}>
    <div class="body"> {# Created because ui.jquery really doesn't like sized <body> #}

    <header class="page-header">
        <h1 class="logo"><a href="/">{% settings_value "SITE_NAME" %}</a></h1>
        {% block logframe_switching_form %}
        {% if request.user and request.user.is_authenticated %}
        <form id="logframes-switch" action="{% url "switch-logframes" %}" method="post">{% csrf_token %}
            <select id="logframes-switch-select" name="logframe" onchange="this.form.submit();"{% if logframe_list|length == 1 %}disabled="disabled"{% endif %}>
            	{% for logframe in logframe_list %}<option value="{{ logframe.id }}"{% if request.user.preferences.last_viewed_logframe == logframe %} selected="selected"{% endif %}>{{ logframe.name }}</option>{% endfor %}
			</select>
		</form>
		{% endif %}
		{% endblock logframe_switching_form %}
        {% if request.user and request.user.is_authenticated %}
         <div class="account-links-auth"><a href="{% url "logout" %}">Log out</a></div>
         {% if perms.contacts.add_user %}
            <div class="navigation-link"><a href="{% url "contact_list" %}" id="nav-people">People</a></li></div>
         {% endif %}
         {% if request.user.preferences.last_viewed_logframe %}
            <div class="navigation-link"><a href="{% url "logframe-dashboard" request.user.preferences.last_viewed_logframe.slug %}" id="nav-dashboard">Dashboard</a></div>
         {% endif %}
         <div class="account-links-profile"><span>Logged in as: </span><a href="{% url "personal_edit" %}">{{ user.get_full_name|default:user.business_email }}</a></div>
        {% else %}
            <div class="account-links-auth"><a href="{% url "login" %}">Log in</a></div>
        {% endif %}
    </header>
    <div class="content-box">
        {% block main_menu %}
        {% if request.user and request.user.is_authenticated %}
        <div class="section-navigation pure-menu pure-menu-open pure-menu-horizontal">
            <ul>
                 
              
                
            </ul>
        </div>
        {% endif %}
        {% endblock main_menu %} 

        {% if messages %}
        <div class="messagelist">
            {% for message in messages %}
            <div class="no-select message message-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="content" id="wrapper">
            {% block content %}{% endblock %}
        </div>
    </div>

    <footer>
        <div class="siteinfo"><p>Built by <a href="http://aptivate.org">Aptivate</a></p></div>
    </footer>
    </div> {# div.body #}
    {% block post_footer %}{% endblock %}
    {% if deploy_env == "staging" or deploy_env == "production" %}
    <script data-main="{{ STATIC_URL }}dist/logframe.min.js" src="{{ STATIC_URL }}js/lib/require.js"></script>
    {% else %}
    <script data-main="{{ STATIC_URL }}js/main.js" src="{{ STATIC_URL }}js/lib/require.js"></script>
    {% endif %}
</body>
</html>

django/website/main/templates/form_snippet.html
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            <div class="pure-control-group">
                <label>
                    <span {{ field.row_attrs }}>{{field.label}}</span>
                    {% if field.help_text %}<span class="help-text">{{ field.help_text|safe }}</span>{% endif %}
                </label>
                {{ field }}
                {% if field.errors %}<span class="field-errors clearfix">{{ field.errors }}</span>{% endif %}
            </div>
        {% endfor %}

django/website/main/templates/main_aside.html
{% extends "base.html" %}

{% block content %}
<section role="main" class="main-column">
    {% block main_content %}{% endblock %}
</section>
<aside class="sidebar">
    {% block sidebar %}{% endblock %}
</aside>
{% endblock %} {# content #}

django/website/main/templates/main_only.html
{% extends "base.html" %}

{% block content %}
<section role="main" class="main-column">
    {% block main_content %}{% endblock %}
</section>
{% endblock %} {# content #}